[2024-09-07T14:50:21.734+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_data_after_retrain.update_data_after_retrain manual__2024-09-07T14:49:53.775452+00:00 [queued]>
[2024-09-07T14:50:21.812+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_data_after_retrain.update_data_after_retrain manual__2024-09-07T14:49:53.775452+00:00 [queued]>
[2024-09-07T14:50:21.814+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-07T14:50:22.017+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): update_data_after_retrain> on 2024-09-07 14:49:53.775452+00:00
[2024-09-07T14:50:22.053+0000] {standard_task_runner.py:60} INFO - Started process 4086 to run task
[2024-09-07T14:50:22.101+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'update_data_after_retrain', 'update_data_after_retrain', 'manual__2024-09-07T14:49:53.775452+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/update_data_after_retrain.py', '--cfg-path', '/tmp/tmpod5rn68q']
[2024-09-07T14:50:22.105+0000] {standard_task_runner.py:88} INFO - Job 150: Subtask update_data_after_retrain
[2024-09-07T14:50:22.281+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-07T14:50:22.660+0000] {task_command.py:423} INFO - Running <TaskInstance: update_data_after_retrain.update_data_after_retrain manual__2024-09-07T14:49:53.775452+00:00 [running]> on host 74653e659746
[2024-09-07T14:50:23.589+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_data_after_retrain' AIRFLOW_CTX_TASK_ID='update_data_after_retrain' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T14:49:53.775452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-07T14:49:53.775452+00:00'
[2024-09-07T14:50:23.788+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-09-07T14:50:23.790+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-09-07T14:50:29.069+0000] {logging_mixin.py:188} INFO - Fichier téléchargé avec succès
[2024-09-07T14:50:29.074+0000] {update_data_after_retrain.py:54} INFO - L'entrainenement est terminé : False
[2024-09-07T14:50:29.076+0000] {update_data_after_retrain.py:56} INFO - Garder le modèle réentrainé : True
[2024-09-07T14:50:29.077+0000] {update_data_after_retrain.py:58} INFO - Data deja intégré dans le modèle : True
[2024-09-07T14:50:29.112+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-07T14:50:29.232+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=update_data_after_retrain, task_id=update_data_after_retrain, execution_date=20240907T144953, start_date=20240907T145021, end_date=20240907T145029
[2024-09-07T14:50:29.694+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-07T14:50:30.028+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
