[2024-08-16T17:11:47.484+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: compare_data2threshold.send2bucket manual__2024-08-16T17:11:29.923577+00:00 [queued]>
[2024-08-16T17:11:47.507+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: compare_data2threshold.send2bucket manual__2024-08-16T17:11:29.923577+00:00 [queued]>
[2024-08-16T17:11:47.508+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-08-16T17:11:47.544+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): send2bucket> on 2024-08-16 17:11:29.923577+00:00
[2024-08-16T17:11:47.552+0000] {standard_task_runner.py:60} INFO - Started process 618 to run task
[2024-08-16T17:11:47.559+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'compare_data2threshold', 'send2bucket', 'manual__2024-08-16T17:11:29.923577+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/compare_data2threshold.py', '--cfg-path', '/tmp/tmpketkvtha']
[2024-08-16T17:11:47.562+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask send2bucket
[2024-08-16T17:11:47.587+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-16T17:11:47.652+0000] {task_command.py:423} INFO - Running <TaskInstance: compare_data2threshold.send2bucket manual__2024-08-16T17:11:29.923577+00:00 [running]> on host 34eae30695aa
[2024-08-16T17:11:47.809+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='compare_data2threshold' AIRFLOW_CTX_TASK_ID='send2bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T17:11:29.923577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T17:11:29.923577+00:00'
[2024-08-16T17:11:47.837+0000] {logging_mixin.py:188} INFO - retrain: False
[2024-08-16T17:11:47.838+0000] {compare_data2threshold.py:116} INFO - retrain value from task 4 : False
[2024-08-16T17:11:47.838+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-16T17:11:47.854+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=compare_data2threshold, task_id=send2bucket, execution_date=20240816T171129, start_date=20240816T171147, end_date=20240816T171147
[2024-08-16T17:11:47.941+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-16T17:11:48.015+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
